# Generated by Django 3.1.1 on 2020-10-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrip', models.CharField(max_length=2000)),
                ('img', models.CharField(max_length=720)),
                ('img1', models.CharField(max_length=2080)),
                ('img2', models.CharField(max_length=2080)),
                ('img3', models.CharField(max_length=2080)),
                ('link', models.CharField(max_length=2080)),
            ],
        ),
    ]
