# Generated by Django 3.1.2 on 2020-10-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='International',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrip', models.CharField(max_length=2000)),
                ('img', models.CharField(max_length=720)),
                ('img1', models.CharField(max_length=2080)),
                ('img2', models.CharField(max_length=2080)),
                ('img3', models.CharField(max_length=2080)),
            ],
        ),
        migrations.AlterField(
            model_name='description',
            name='img',
            field=models.CharField(max_length=720),
        ),
    ]
