# Generated by Django 3.1.2 on 2020-10-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0002_auto_20201008_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='International',
        ),
    ]
