# Generated by Django 3.1.2 on 2020-10-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0004_auto_20201027_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fname',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lname',
            field=models.CharField(default='', max_length=122),
        ),
    ]
