# Generated by Django 3.1.2 on 2020-10-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0005_auto_20201027_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fname',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lname',
            field=models.CharField(max_length=122),
        ),
    ]
